name: Release
on:
  push:
    branches:
      - main # You may need to change this to master
      - develop

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load npm cache
        uses: actions/cache@v2
        id: loadCache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          # no restore-keys here, so we only accept this exact version
      - name: Install npm packages
        if: ${{ steps.loadCache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release